---
- name: Ensure Watchtower API key
  ansible.builtin.template:
    src: authentik_secret.j2
    dest: "{{ hms_docker_data_path }}/.watchtower.key"
    mode: 0600
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    force: no
  no_log: true
  register: watchtower_key_output
  vars:
    key: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

- name: Slurp Watchtower key data
  ansible.builtin.slurp:
    src: "{{ watchtower_key_output.dest }}"
  register: slurped_watchtower_key_data
  check_mode: false
  when: watchtower_key_output.dest is defined
  no_log: true

- name: Ensure homepage docker config
  ansible.builtin.copy:
    src: homepage_docker.yaml
    dest: "{{ hms_docker_apps_path }}/homepage/config/docker.yaml"
    mode: 0644
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    force: no
    
- name: Ensure homepage services config
  ansible.builtin.copy:
    src: homepage_services.yaml
    dest: "{{ hms_docker_apps_path }}/homepage/config/services.yaml"
    mode: 0644
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    force: no
