---
- name: Ensure CIFS packages.
  ansible.builtin.package:
    name:
      - cifs-utils
      - samba-client
      - samba-common
    state: "{{ nas_client_package_state }}"

- name: Ensure CIFS credentials file.
  ansible.builtin.template:
    dest: "{{ hms_docker_data_path }}/.{{ project_name }}.cifs_creds"
    src: cifs_creds.j2
    owner: root
    group: root
    mode: 0600
  vars:
    username: "{{ nas_client_cifs_username }}"
    password: "{{ nas_client_cifs_password }}"
  register: cifs_creds_file

- name: Ensure CIFS fstab entry.
  ansible.posix.mount:
    backup: yes
    boot: "{{ nas_client_mount_on_boot }}"
    path: "{{ hmsdocker_primary_mount_path }}"
    src: "{{ nas_client_remote_cifs_path }}"
    fstype: cifs
    opts: credentials={{ cifs_creds_file.dest }},{{ nas_client_cifs_opts }}
    state: "{{ nas_client_mount_state }}"
  when:
    - cifs_creds_file is defined
    - not ansible_check_mode
