# The container map, use this to disable specific containers from running or being accessible by Traefik

# Values:
#  `authentik`: Enables or disables accessing the container via Authentik
#  `authentik_provider_type`: The type of Authentik provider. Default is `proxy`, add with value of `oauth2` (authentik_provider_type: oauth2) if you know the service uses OAuth2
#  `directory`: Creates the container directory within the apps folder
#  `enabled`: Enables or disables the container
#  `expose_ports`: Enables the container ports to be open on the host (so you can access the containers via <IP>:<port>)
#  `expose_to_public`: Enables or disables exposing the container to the public internet via Traefik (removes allowlist restrictions, does not expose the container port)
#  `homepage`: Enables or disables Homepage container integration (if supported)
#  `homepage_stats`: Displays the container stats in Homepage (CPU, RAM, network traffic)
#  `proxy_host_rules`: Sets the host rules for the container (so you can access the container via "http://<host>.<domain>")
#  `traefik`: Enables or disables accessing the container via Traefik

hms_docker_container_map:
  authentik:
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: authentik
    traefik: true
  autobrr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: autobrr
    traefik: true
  backrest:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: backrest
    traefik: true
  bazarr:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: bazarr
    traefik: true
  calibre:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: calibre
    traefik: true
  checkrr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: checkrr
    traefik: true
  cleanuparr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: cleanuparr
    traefik: true
  cloudflare-ddns:
    enabled: false
  cloudflare-tunnel:
    enabled: false
    homepage: false
    homepage_stats: false
  cross-seed:
    directory: true
    enabled: false
    expose_ports: false
  deluge:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: deluge
    traefik: true
  dispatcharr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: dispatcharr
    traefik: true
  emby:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: emby
    traefik: true
  fileflows:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: fileflows
    traefik: true
  flaresolverr:
    enabled: false
    expose_ports: false
  heimdall:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: heimdall
    traefik: true
  homepage:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: homepage
    traefik: true
  huntarr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: huntarr
    traefik: true
  jellyfin:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: jellyfin
    traefik: true
  jellyseerr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: jellyseerr
    traefik: true
  kavita:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: kavita
    traefik: true
  lidarr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: lidarr
    traefik: true
  maintainerr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: maintainerr
    traefik: true
  n8n:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: n8n
    traefik: true
  netdata:
    enabled: false
    homepage: true
    homepage_stats: false
  notifiarr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: notifiarr
    traefik: true
  nzbget:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: nzbget
    traefik: true
  overseerr:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: overseerr
    traefik: true
  pasta:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: pasta
    traefik: true
  pinchflat:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: pinchflat
    traefik: true
  plex:
    authentik: false
    directory: true
    enabled: true
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: plex
    traefik: true
  portainer:
    authentik: false
    authentik_provider_type: oauth2
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: portainer
    traefik: true
  prowlarr:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: prowlarr
    traefik: true
  qbittorrent:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: qbittorrent
    traefik: true
  radarr:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: radarr
    traefik: true
  recyclarr:
    directory: true
    enabled: false
  requestrr:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: requestrr
    traefik: true
  sabnzbd:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: sabnzbd
    traefik: true
  sonarr:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: sonarr
    traefik: true
  speedtest-tracker:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: speedtest
    traefik: true
  tailscale:
    enabled: false
    homepage: false
    homepage_stats: false
  tautulli:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: tautulli
    traefik: true
  tdarr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: tdarr
    traefik: true
  tinymediamanager:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: tmm
    traefik: true
  tracearr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: tracearr
    traefik: true
  traefik:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: false
    proxy_host_rule: traefik
    traefik: true
  transmission:
    authentik: false
    directory: true
    enabled: true
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: transmission
    traefik: true
  tubearchivist:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: tubearchivist
    traefik: true
  unmanic:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: unmanic
    traefik: true
  unpackerr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: unpackerr
    traefik: true
  uptimekuma:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    homepage: true
    homepage_stats: true
    proxy_host_rule: uptime-kuma
    traefik: true
  watchtower:
    enabled: true
    homepage: true
    homepage_stats: false
  wizarr:
    authentik: false
    directory: true
    enabled: false
    expose_ports: false
    expose_to_public: false
    proxy_host_rule: wizarr
    traefik: true
