# The container map, use this to disable specific containers from running or being accessible by Traefik
# Values:
#  `enabled`: Enables or disables the container
#  `proxy_host_rules`: Sets the host rules for the container (so you can access the container via "http://<host>.<domain>")
#  `directory`: Creates the container directory within the apps folder
#  `traefik`: Enables or disables accessing the container via Traefik
#  `authentik`: Enables or disables accessing the container via Authentik
#  `authentik_provider_type`: Enables or disables accessing the container via Authentik HTTP Proxy. Disable if application does NOT need an additional proxy layer (such as for OAuth or OpenID Connect)
#  `expose_to_public`: Enables or disables exposing the container to the public internet via Traefik (removes allowlist restrictions, does not expose the container port)
#  `homepage`: Enables or disables Homepage container integration (if supported)
#  `homepage_stats`: Displays the container stats in Homepage (CPU, RAM, network traffic)

hms_docker_container_map:
  traefik:
    enabled: yes
    proxy_host_rule: traefik
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
  sonarr:
    enabled: yes
    proxy_host_rule: sonarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  radarr:
    enabled: yes
    proxy_host_rule: radarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  bazarr:
    enabled: yes
    proxy_host_rule: bazarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  transmission:
    enabled: yes
    proxy_host_rule: transmission
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  portainer:
    enabled: yes
    proxy_host_rule: portainer
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: oauth2
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  overseerr:
    enabled: yes
    proxy_host_rule: overseerr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  jellyseerr:
    enabled: no
    proxy_host_rule: jellyseerr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  prowlarr:
    enabled: yes
    proxy_host_rule: prowlarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  requestrr:
    enabled: yes
    proxy_host_rule: requestrr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  plex:
    enabled: yes
    proxy_host_rule: plex
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  tautulli:
    enabled: yes
    proxy_host_rule: tautulli
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  nzbget:
    enabled: no
    proxy_host_rule: nzbget
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  sabnzbd:
    enabled: no
    proxy_host_rule: sabnzbd
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  authentik:
    enabled: no
    proxy_host_rule: authentik
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  tdarr:
    enabled: no
    proxy_host_rule: tdarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  homepage:
    enabled: no
    proxy_host_rule: homepage
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  uptimekuma:
    enabled: no
    proxy_host_rule: uptime-kuma
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  heimdall:
    enabled: no
    proxy_host_rule: heimdall
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  readarr:
    enabled: no
    proxy_host_rule: readarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: no
  kavita:
    enabled: no
    proxy_host_rule: kavita
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  calibre:
    enabled: no
    proxy_host_rule: calibre
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  jellyfin:
    enabled: no
    proxy_host_rule: jellyfin
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  emby:
    enabled: no
    proxy_host_rule: emby
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  maintainerr:
    enabled: no
    proxy_host_rule: maintainerr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  unpackerr:
    enabled: no
    proxy_host_rule: unpackerr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  lidarr:
    enabled: no
    proxy_host_rule: lidarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  autobrr:
    enabled: no
    proxy_host_rule: autobrr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
    homepage: yes
    homepage_stats: yes
  notifiarr:
    enabled: no
    proxy_host_rule: notifiarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  speedtest-tracker:
    enabled: no
    proxy_host_rule: speedtest
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  recyclarr:
    enabled: no
    directory: yes
  tinymediamanager:
    enabled: no
    proxy_host_rule: tmm
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  pasta:
    enabled: no
    proxy_host_rule: pasta
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
  netdata:
    enabled: no
  wizarr:
    enabled: no
    proxy_host_rule: wizarr
    directory: yes
    traefik: yes
    authentik: no
    authentik_provider_type: proxy
    expose_to_public: no
