# Other keys not listed here may be retrieved during a playbook run from the apps config file

# NZB
homepage_nzbget_key: 

# Authentik
homepage_authentik_key: 

# Portainer
homepage_portainer_key: 

# Jellyfin
homepage_jellyfin_key: 

# Emby
homepage_emby_key: 

# Autobrr
homepage_autobrr_key: 
