# Other keys not listed here may be retrieved during a playbook run from the apps config file

# NZB
homepage_nzbget_key: 

# Authentik
# See: https://gethomepage.dev/widgets/services/authentik/
homepage_authentik_key: 

# Portainer
homepage_portainer_key: 

# Jellyfin
homepage_jellyfin_key: 

# Emby
homepage_emby_key: 

# Autobrr
homepage_autobrr_key: 

# Backrest
hmsdocker_homepage_backrest_user: 
hmsdocker_homepage_backrest_pass: 

# Cloudflare Tunnel
# API key requires permissions: Account.Cloudflare Tunnel:Read
hmsdocker_homepage_cftunnel_key: 
hmsdocker_homepage_cftunnel_accountid: 
hmsdocker_homepage_cftunnel_tunnelid: 

# Tailscale
hmsdocker_homepage_tailscale_api_key: 
hmsdocker_homepage_tailscale_device_id: 

# Speedtest Tracker
hmsdocker_homepage_speedtest_api_key:

# Tubearchivist
hmsdocker_homepage_tubearchivist_api_key: 

# Uptime Kuma
# Input the "slug" for the status page you want to monitor (example: `uptimekuma.example.com/status/hmsdocker` you would input `hmsdocker`)
hmsdocker_homepage_uptimekuma_statuspage_slug: 

# Dockhand credentials
hmsdocker_homepage_dockhand_user:
hmsdocker_homepage_dockhand_pass: 
