---
- name: Ensure Packages
  package:
    name: "{{ item }}"
    state: "{{ gpu_prereq_packages_state }}"
  loop:
    - tar
    - bzip2
    - make
    - automake
    - gcc
    - gcc-c++
    - vim
    - pciutils
    - elfutils-libelf-devel
    - libglvnd-devel
    - kernel-devel

- name: Ensure libnvidia Docker repo
  yum_repository:
    name: libnvidia-container
    description: libnvidia-container
    file: nvidia-container-runtime
    baseurl: https://nvidia.github.io/libnvidia-container/stable/{{ gpu_distribution_override | lower }}{{ ansible_facts['distribution_major_version'] }}/$basearch
    enabled: 1
    gpgcheck: 0
    repo_gpgcheck: 1
    gpgkey: https://nvidia.github.io/libnvidia-container/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Ensure libnvidia experimental Docker repo
  yum_repository:
    name: libnvidia-container-experimental
    description: libnvidia-container-experimental
    file: nvidia-container-runtime
    baseurl: https://nvidia.github.io/libnvidia-container/experimental/{{ gpu_distribution_override | lower }}{{ ansible_facts['distribution_major_version'] }}/$basearch
    enabled: 0
    gpgcheck: 0
    repo_gpgcheck: 1
    gpgkey: https://nvidia.github.io/libnvidia-container/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Ensure Nvidia Container Runtime repo
  yum_repository:
    name: nvidia-container-runtime
    description: nvidia-container-runtime
    file: nvidia-container-runtime
    baseurl: https://nvidia.github.io/nvidia-container-runtime/stable/{{ gpu_distribution_override | lower }}{{ ansible_facts['distribution_major_version'] }}/$basearch
    enabled: 1
    gpgcheck: 0
    repo_gpgcheck: 1
    gpgkey: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Ensure nvidia container runtime experimental repo
  yum_repository:
    name: nvidia-container-runtime-experimental
    description: nvidia-container-runtime-experimental
    file: nvidia-container-runtime
    baseurl: https://nvidia.github.io/nvidia-container-runtime/experimental/{{ gpu_distribution_override | lower }}{{ ansible_facts['distribution_major_version'] }}/$basearch
    enabled: 0
    gpgcheck: 0
    repo_gpgcheck: 1
    gpgkey: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
